USE api_ionic;

-- TIPO DE CONTRATAÇÃO --
INSERT INTO tipo_contratacao (cont_descricao) VALUES ("CLT");
INSERT INTO tipo_contratacao (cont_descricao) VALUES ("PJ");
INSERT INTO tipo_contratacao (cont_descricao) VALUES ("Estagiário");
INSERT INTO tipo_contratacao (cont_descricao) VALUES ("Temporário");

SELECT * FROM tipo_contratacao;

-- DEPARTAMENTOS -- 
INSERT INTO departamento (dep_descricao, dep_head) VALUES ("RH", "Diretor de RH");
INSERT INTO departamento (dep_descricao, dep_head) VALUES ("TI", "Diretor de TI");
INSERT INTO departamento (dep_descricao, dep_head) VALUES ("Marketing", "Diretor de Marketing");
INSERT INTO departamento (dep_descricao, dep_head) VALUES ("Finanças", "Diretor Financeiro");
INSERT INTO departamento (dep_descricao, dep_head) VALUES ("Vendas", "Diretor de Vendas");
INSERT INTO departamento (dep_descricao, dep_head) VALUES ("Produção", "Diretor de Produção");

SELECT * FROM departamento;

-- CARGOS --
-- RH
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Diretor de RH", 1, 1);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Administrador de RH", 1, 1);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Consultor de RH", 2, 1);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Assistente de Departamento Pessoal", 0, 1);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Supervisor de Cargos", 0, 1);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Analista de RH", 0, 1);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Estagiário de RH", 0, 1);
-- TI
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Diretor de TI", 1, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Gerente Técnico", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Gerente de TI", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Gerente de Software", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Gerente de Segurança de TI", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Administrador de Banco de Dados", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Administrador de Redes", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00, "Arquiteto da Informação", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Administrador de E-commerce", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Administrador de Processamento de Dados", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Qualidade de Software", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Segurança da Informação", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Sistemas", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Suporte Técnico de TI", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Engenheiro de Software", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Engenheiro de Dados", 0, 2);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Estagiário de TI", 0, 2);
-- Marketing
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Diretor de Marketing", 1, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Marketing", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Coordenador de Marketing", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Marketing", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Marketing", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Mídias Sociais", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de SEO", 0, 3); -- Search Engine Optimization
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de CRO", 0, 3); -- Conversion Rate Optmization
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de UX", 0, 3); -- User Experience
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Cientista de Dados", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Qualidade", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Atendimento", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Marcas", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Programador Front-End", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Programador Back-End", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Arquiteto de Software", 0, 3);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Estagiário de Marketing", 0, 3);
-- Finanças
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Diretor Financeiro", 1, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente Contábil", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista Contábil", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista Estatístico", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Especialista de Planejamento Financeiro", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Compliance", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Compliance", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Consultor de Investimento", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Finanças Estruturadas", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Controller", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Crédito", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Fusões e Aquisições", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Conselheiro de Aposentadoria", 0, 4);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Estagiário de Finanças", 0, 4);
-- Vendas
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Diretor de Vendas", 1, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Supervisor de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Coordenador de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Consultor de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Suporte a Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Auxiliar de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Auxiliar Administrativo de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gestor de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Inside Seller", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Customer Experience", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Representante de Desenvolvimento de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Promotor de Vendas", 0, 5);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Pós-Vendas", 0, 5);
-- Produção
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Diretor de Produção", 1, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Gerente de Produção", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Analista de Desempenho", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Supervisor de Linha", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Apontador de Produção", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Programador CND", 0, 6); -- Coordena máquinas de Comando Numérico Computadorizado
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Programador da Produção", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Operador de Máquina", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Administrador de Almoxarife", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"Almoxarife", 0, 6);
INSERT INTO cargo (car_vale_transporte, car_vale_refeicao, car_auxilio_creche, car_plano_saude, car_salario, car_descricao, car_nivel_acesso, departamento_dep_id) VALUES (1000.00, 1000.00, 1400.00, "Sulamérica", 15000.00,"CEO", 1, 1);

SELECT * FROM cargo;

-- COLABORADOR --
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("jose.leovigildo@ionic.health", "1234", "José Leovigildo Coelho", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "81", "1", "Física",30870722069, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("milla.moreira@ionic.health", "1234", "Milla Moreira", "12", "986571945", "Rua Ferdinando Lima", "47", "Alphaville", "17845134", "SP", "", "Sudeste", "1", "1", "1", "Física",1,94821526034, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("anna.costa@ionic.health", "1234", "Anna Costa", "12", "986571735", "Rua Hortência Melo", "14", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "3", "1", "Física", 2,69434866081, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("joao.almeida@ionic.health", "1234", "João Almeida", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "3", "7", "1", "Física", 2,04679437022, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("camila.monteiro@ionic.health", "1234", "Camila Monteiro", "12", "986571245", "Rua Estados Unidos", "78", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "8", "2", "Física",1,34604730024, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("flavia.alves@ionic.health", "1234", "Flávia Alves", "12", "977574245", "Alameda das Laranjeiras", "23", "Novo Horizonte", "75245134", "SP", "", "Sudeste", "1", "10", "2", "Física", 5,80634156047, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("matheus.sakuragui@ionic.health", "1234", "Matheus Sakuragui", "12", "986571245", "Rua Estados Unidos", "47", "Putim", "12245134", "SP", "", "Sudeste", "4", "18", "2", "Física", 6,01607663031, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("roberta.lima@ionic.health", "1234", "Roberta Lima", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "3", "25", "3", "Física", 1,14820696017, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("gizeli.fonseca@ionic.health", "1234", "Gizeli Fonseca", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "3", "26", "3", "Física",8,34754107020, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("mariana.ayumi@ionic.health", "1234", "Mariana Ayumi", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "34", "2", "Física", 5,74481612029, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("emerson.araujo@ionic.health", "1234", "Emerson Araujo", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "42", "4", "Física", 1,24416217005, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("adriana.font@ionic.health", "1234", "Adriana Font", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "43", "4", "Física",11,80911020039, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("fernando.poli@ionic.health", "1234", "Fernando Poli", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "46", "4", "Física", 12,17872352036, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("rikio.anzai@ionic.health", "1234", "Rikio Anzai", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "3", "56", "5", "Física", 1, 41515407098, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("maria.faria@ionic.health", "1234", "Maria Clara Faria", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "71", "6", "Física",1,21413528007, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("lucas.santos@ionic.health", "1234", "Lucas Santos", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "62", "5", "Física", 14,88097159007, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id,col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("rodrigo.silva@ionic.health", "1234", "Rodrigo Silva", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "4", "70", "5", "Física", 14,85288300046, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa,col_head_id, col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("janaina.gusmao@ionic.health", "1234", "Janaína Gusmão", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "72", "6", "Física", 15, 48636127025, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id, col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("gabriel.telles@ionic.health", "1234", "Gabriel Telles", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "76", "6", "Física", 15, 05604765074, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');
INSERT INTO colaborador (col_email, col_senha, col_nome, col_ddd, col_telefone, col_end_rua, col_end_numero, col_end_bairro, col_end_cep, col_end_estado, col_end_complemento, col_end_regiao, tipo_contratacao_cont_id, cargo_car_id, departamento_dep_id, col_tipo_pessoa, col_head_id, col_cpf, col_data_nascimento, col_raca, col_naturalidade, col_genero, col_nacionalidade, col_estado_civil, col_filho) VALUES ("leonardo.salles@ionic.health", "1234", "Leonardo Salles", "12", "986571245", "Rua Estados Unidos", "47", "Vista Verde", "12245134", "SP", "", "Sudeste", "1", "80", "6", "Física", 15, 21804846074, '1989-12-13', 'Amarelo', 'São José dos Campos', 'Feminino', 'Brasileiro', 'Solteiro', 'Não');

SELECT * FROM colaborador;

SELECT colab.departamento_dep_id, colab.col_nome, car.car_descricao, dep_descricao 
FROM colaborador colab 
INNER JOIN cargo car INNER JOIN departamento dep 
ON colab.departamento_dep_id = dep.dep_id 
AND colab.cargo_car_id = car.car_id;

-- QUALIFICAÇÃO -- 
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (1, 'FATEC', 'Superior', 'DSM', 'Inglês', 1);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (2, 'FATEC', 'Superior', 'DSM', 'Inglês', 2);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (3, 'FATEC', 'Superior', 'DSM', 'Inglês', 3);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (4, 'FATEC', 'Superior', 'DSM', 'Inglês', 4);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (5, 'FATEC', 'Superior', 'DSM', 'Inglês', 5);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (6, 'FATEC', 'Superior', 'DSM', 'Inglês', 6);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (7, 'FATEC', 'Superior', 'DSM', 'Inglês', 7);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (8, 'FATEC', 'Superior', 'DSM', 'Inglês', 8);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (9, 'FATEC', 'Superior', 'DSM', 'Inglês', 9);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (10, 'FATEC', 'Superior', 'DSM', 'Inglês', 10);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (11, 'FATEC', 'Superior', 'DSM', 'Inglês', 11);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (12, 'FATEC', 'Superior', 'DSM', 'Inglês', 12);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (13, 'FATEC', 'Superior', 'DSM', 'Inglês', 13);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (14, 'FATEC', 'Superior', 'DSM', 'Inglês', 14);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (15, 'FATEC', 'Superior', 'DSM', 'Inglês', 15);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (16, 'FATEC', 'Superior', 'DSM', 'Inglês', 16);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (17, 'FATEC', 'Superior', 'DSM', 'Inglês', 17);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (18, 'FATEC', 'Superior', 'DSM', 'Inglês', 18);
INSERT INTO qualificacao (qua_id, qua_nome_instituicao, qua_formacao, qua_curso, qua_lingua, colaborador_col_id) VALUES (19, 'FATEC', 'Superior', 'DSM', 'Inglês', 19);

SELECT * FROM qualificacao;

-- ACESSO AO SISTEMA --
INSERT INTO colaborador (col_email, col_senha)  VALUES ('adm@ionic.health', '1234'); 